database_file: "./db/matrix.db"
menu_program: "wofi --show drun"
fov: 45.0
zFar: 400.0
background:
  enabled: false
  model_path: "models/background.obj"
  position: [0, 0, -10]
  scale: 1.0
backface_texture:
  enabled: false
  texture_path: "images/backface.png"
key_mappings:
  screenshot: "p"
  toggle_cursor: "f"
  quit: "escape"
  super_modifier: "super"
  window_larger: "bracketright"
  window_smaller: "bracketleft"
  move_forward: "w"
  move_backward: "s"
  move_left: "a"
  move_right: "d"
  move_up: "space"
  move_down: "left_shift"
  toggle_meshing: "m"
  toggle_wireframe: "slash"
  save: "l"
  menu: "v"
  reset_speed: "0"
  speed_up: "equal"
  speed_down: "minus"
